---
title: "Linear Model Selection and Regularization in R"
author: "Jeremy Williams"
date: "April 30, 2018"
output:
  pdf_document:
    fig_height: 4
    fig_width: 6
    toc: yes
    toc_depth: 2
  html_document:
    fig_height: 4
    fig_width: 6
    toc: yes
    toc_depth: 2
subtitle: Mathematics for Big Data (R Coding Questions)
---

\newpage
# Exercise 3

Suppose we estimate the regression coefficients in a linear regression model by minimising
$$
\sum_{i=1}^{n}\left (y_{i} -\beta_{0} -\sum_{j=1}^{p}\beta_{j}x_{ij}\right )\quad \text{subject to}\quad \sum_{j=1}^{p}\vert \beta_{j}\vert \leq s
$$

for a particular value of $s$. For parts (a) through (e), indicate which of i. through v. is correct. Justify your answer.

(a) As we increase $s$ from 0, the training RSS will:
	i. Increase initially, and then eventually start decreasing in an inverted U shape.
	ii. Decrease initially, and then eventually start increasing in a U shape.
	iii. Steadily increase.
	iv. Steadily decrease.
	v. Remain constant.

(b) Repeat (a) for test RSS.
 
(c) Repeat (a) for variance.
 
(d) Repeat (a) for (squared) bias.
 
(e) Repeat (a) for the irreducible error.


\newpage
# Exercise 5

	
It is well-known that Ridge regression tends to give similar coefficient values to correlated variables, whereas the Lasso may give quite different coefficient values to correlated variables. We will now explore this property in a very simple setting.

Suppose that $n = 2$, $p = 2$, $x_{11} = x_{12}$, $x_{21} = x_{22}$. Furthermore, suppose that $y_{1} + y_{2} = 0$ and $x_{11} + x_{21} = 0$ and $x_{12} + x_{22} = 0$, so that the estimate for the intercept in a least squares, Ridge regression, or Lasso model is zero: $\hat{\beta}_{0} = 0$.

(a) Write out the Ridge regression optimisation problem in this setting.
 
(b) Argue that in this setting, the Ridge coefficient estimates satisfy $\hat{\beta}_{1} =\hat{\beta}_{2}$.
 
(c) Write out the Lasso optimisation problem in this setting.
 
(d) Argue that in this setting, the Lasso coefficients $\hat{\beta}_{1}$ and $\hat{\beta}_{2}$ are not unique; in other words, there are many possible solutions to the optimisation problem in (c). Describe these solutions.


\newpage
# Exercise 8
	
In this exercise, we will generate simulated data, and will then use this data to perform best subset selection.

(a) Use the `rnorm()` function to generate a predictor $X$ of length $n = 100$, as well as a noise vector $\epsilon$ of length $n = 100$.
 
(b) Generate a response vector $Y$ of length $n = 100$ according to the model
$$
Y = \beta_{0} + \beta_{1}X + \beta_{2}{X}^{2} + \beta_{3}{X}^{3} + \epsilon,
$$
 
where $\beta_{0}$, $\beta_{1}$, $\beta_{2}$, and $\beta_{3}$ are constants of your choice.
 
(c) Use the `regsubsets()` function to perform best subset selection in order to choose the best model containing the predictors $X, {X}^{2}, \dots, {X}^{10}$. What is the best model obtained according to $C_{p}$, $BIC$, and adjusted $R^{2}$? Show some plots to provide evidence for your answer, and report the coefficients of the best model obtained.
 
(d) Repeat (c), using forward stepwise selection and also using backwards stepwise selection. How does your answer compare to the results in (c)?
 
(e) Now fit a Lasso model to the simulated data, again using $X, {X}^{2}, \dots, {X}^{10}$ as predictors. Use cross-validation to select the optimal value of $\lambda$. Create plots of the cross-validation error as a function of $\lambda$. Report the resulting coefficient estimates, and discuss the results obtained.
 
(f) Now generate a response vector $Y$ according to the model

$$
Y = \beta_{0} + \beta_{7} {X}^{7} + \epsilon,
$$  
 
and perform best subset selection and the Lasso. Discuss the results obtained.

\newpage
# Exercise 9

In this exercise, we will predict the number of applications received using the other variables in the `College` data set.

(a) Split the data set into a training set and a test set.
 
(b) Fit a linear model using least squares on the training set, and report the test error obtained.
 
(c) Fit a Ridge regression model on the training set, with $\lambda$ chosen by cross-validation. Report the test error obtained.
 
(d) Fit a Lasso model on the training set, with $\lambda$ chosen by cross-validation. Report the test error obtained, along with the number of non-zero coefficient estimates.
 
(g) Comment on the results obtained. How accurately can we predict the number of college applications received? Is there much difference among the test errors resulting from these five approaches?


\newpage
# Exercise 10

We have seen that as the number of features used in a model increases, the training error will necessarily decrease, but the test error may not. We will now explore this in a simulated data set.

(a) Generate a data set with $p = 20$ features, $n = 1000$ observations, and an associated quantitative response vector generated according to the model
$$
Y = X \cdot \beta +\epsilon,
$$
where $\beta$ has some elements that are exactly equal to zero.
 
(b) Split your data set into a training set containing 100 observations and a test set containing 900 observations.
 
(c) Perform best subset selection on the training set, and plot the training set MSE associated with the best model of each size.
 
(d) Plot the test set MSE associated with the best model of each size.
 
(e) For which model size does the test set MSE take on its minimum value? Comment on your results. If it takes on its minimum value for a model containing only an intercept or a model containing all of the features, then play around with the way that you are generating the data in (a) until you come up with a scenario in which the test set MSE is minimized for an intermediate model size.
 
(f)	
How does the model at which the test set MSE is minimized compare to the true model used to generate the data? Comment on the coefficient values.
 
(g) Create a plot displaying $\sqrt{\sum_{j=1}^{p}{(\beta_{j} -\hat{\beta}_{j}^{r})}^{2}}$ for a range of values of $r$, where $\hat{\beta}_{j}^{r}$ is the $j$th coefficient estimate for the best model containing $r$ coefficients. Comment on what you observe. How does this compare to the test MSE plot from (d)?

